[package]
name = "cascii-terminal-decorator"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
cascii-core-view = { path = "../cascii-core-view" }
crossterm = "0.28"
